project:
  type: book

book:
  title: "NFL Football Analytics"
  subtitle: "Version 0.0.1"
  author: "Your Name"
  date: today
  sharing: [twitter, facebook, linkedin]
  license: "CC BY"
  reader-mode: true
  page-footer:
    left: |
      "NFL Football Analytics" was written by <a href="#">Your Name</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/MargareeMan/Fantasy-Football-Analytics-Textbook
  repo-branch: main
  repo-actions: [edit, source, issue]
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Base Performance Descriptive Statistics"
      chapters:
        - weekly-performance.qmd
        - annual-performance.qmd
        - team-weekly-performance.qmd
        - team-season-statistics.qmd
        - career-statistics.qmd
    - part: "Modelling Play, Player, and Team Performance"
      chapters:
        - regression.qmd
        - multiple-regression.qmd
        - glm.qmd
        - glmm.qmd
    - part: "Advanced Modelling Approaches"
      chapters:
        - bayesian-hierarchical.qmd
        - machine-learning-advanced.qmd
        - pca.qmd
        - cluster-analysis.qmd
        - factor-analysis.qmd
        - time-series.qmd
    - part: "Machine Learning"
      chapters:
        - machine-learning.qmd
    - part: "Causal Inference"
      chapters:
        - causal-inference.qmd
    - part: "Prediction and Forecasting"
      chapters:
        - prediction-forecasting.qmd
    - part: "Appendices"
      chapters:
        - appendix-github.qmd
        - appendix-statistical-modelling.qmd
        - appendix-nfl-analytics.qmd
        - appendix-r-notes.qmd
    - references.qmd

bibliography: [references.bib, packages.bib]
csl: apa.csl

format:
  html:
    highlight-style: a11y
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-link: true
    number-sections: true
    code-fold: show
    code-line-numbers: true
    toc: true
    toc-depth: 5
    execute:
      error: true
      message: false
      warning: false
    link-external-newwindow: true
    anchor-sections: true
    df-print: paged

lightbox:
  match: auto
